/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author ELCOT
 */
public class AdminAnalyticalPage extends javax.swing.JFrame  implements Runnable {

    /**
     * Creates new form AnalitcalPage
     */
    
    //Sqlite connection
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
   static String from;
   static String to;
   static int FriendsCount;
   static int AdvertisementCount ;
   static int OtherCount;
   static int PamphletCount;
   static int noneCount;
   static int OnlineCount;
   int hour,minute,second;
   Thread t=new Thread(this);
    
    ImageIcon icon;
    
    //From and To date need this
     
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    
    public AdminAnalyticalPage() {
        initComponents();
            ShowDate.setText(String.valueOf(java.time.LocalDate.now()));
          t.start();
         con=ConnectionDb.DbConnection();
         icon= new ImageIcon("D:\\Regestation form\\Software\\Logo (2).png");
        setIconImage(icon.getImage());
    }
    
     @Override
      public void run(){
        while(true){
        Calendar cal=Calendar.getInstance();
        hour = cal.get(Calendar.HOUR_OF_DAY); 
        minute= cal.get (Calendar.MINUTE);
        second= cal.get (Calendar.SECOND);
        
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        Date dat=cal.getTime();
        String Time=sdf.format(dat);
        Showtime.setText(Time);
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        MonthShowChart = new javax.swing.JPanel();
        MonthChartButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MonthFromDate = new com.toedter.calendar.JDateChooser();
        MonthToDate = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        RefferenceShowChart = new javax.swing.JPanel();
        RefferenceCharButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RefferenceFromDate = new com.toedter.calendar.JDateChooser();
        RefferenceToDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        RegistrationShowChart = new javax.swing.JPanel();
        RegistrationChartButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegistratonFromDate = new com.toedter.calendar.JDateChooser();
        RegistratonToDate = new com.toedter.calendar.JDateChooser();
        ShowDate = new javax.swing.JLabel();
        Showtime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("AnalyticalPage");

        jPanel3.setBackground(new java.awt.Color(51, 0, 255));

        MonthShowChart.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MonthShowChartLayout = new javax.swing.GroupLayout(MonthShowChart);
        MonthShowChart.setLayout(MonthShowChartLayout);
        MonthShowChartLayout.setHorizontalGroup(
            MonthShowChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MonthShowChartLayout.setVerticalGroup(
            MonthShowChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        MonthChartButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        MonthChartButton.setText("Show Chart");
        MonthChartButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MonthChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthChartButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("TO");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("FROM");

        MonthFromDate.setDateFormatString("yyyy-MM-dd");

        MonthToDate.setDateFormatString("yyyy-MM-dd");
        MonthToDate.setMinSelectableDate(new java.util.Date(-62135785719000L));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MonthShowChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(55, 55, 55)
                .addComponent(MonthFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jLabel3)
                .addGap(87, 87, 87)
                .addComponent(MonthToDate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(MonthChartButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(MonthShowChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MonthFromDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(MonthToDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(MonthChartButton)))
                .addGap(45, 45, 45))
        );

        jTabbedPane2.addTab("Month", jPanel3);

        RefferenceShowChart.setBackground(new java.awt.Color(255, 255, 255));
        RefferenceShowChart.setLayout(new java.awt.BorderLayout());

        RefferenceCharButton.setText("Show Chart");
        RefferenceCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefferenceCharButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("TO");

        jLabel2.setText("FROM");

        RefferenceFromDate.setDateFormatString("yyyy-MM-dd");

        RefferenceToDate.setDateFormatString("yyyy-MM-dd");
        RefferenceToDate.setMinSelectableDate(new java.util.Date(-62135785719000L));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RefferenceShowChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(RefferenceFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(RefferenceToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(RefferenceCharButton)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RefferenceShowChart, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RefferenceCharButton)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addComponent(RefferenceFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RefferenceToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reffference", jPanel1);

        jTabbedPane1.addTab("Enquiry", jTabbedPane2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RegistrationShowChartLayout = new javax.swing.GroupLayout(RegistrationShowChart);
        RegistrationShowChart.setLayout(RegistrationShowChartLayout);
        RegistrationShowChartLayout.setHorizontalGroup(
            RegistrationShowChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        RegistrationShowChartLayout.setVerticalGroup(
            RegistrationShowChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        RegistrationChartButton.setText("Show Chart");
        RegistrationChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationChartButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("TO");

        jLabel7.setText("FROM");

        RegistratonFromDate.setDateFormatString("yyyy-MM-dd");

        RegistratonToDate.setDateFormatString("yyyy-MM-dd");
        RegistratonToDate.setMinSelectableDate(new java.util.Date(-62135785719000L));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistrationShowChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel7)
                .addGap(75, 75, 75)
                .addComponent(RegistratonFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(60, 60, 60)
                .addComponent(RegistratonToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(RegistrationChartButton)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(RegistrationShowChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegistrationChartButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addComponent(RegistratonFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(RegistratonToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registration", jPanel2);

        ShowDate.setBackground(new java.awt.Color(255, 255, 255));
        ShowDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Showtime.setBackground(new java.awt.Color(255, 255, 255));
        Showtime.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Showtime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(ShowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Showtime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         AdminOptionForm adminoption = new AdminOptionForm();
                 adminoption.setVisible(true);
                 dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    
  
    private void RefferenceCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefferenceCharButtonActionPerformed
        // TODO add your handling code here:
          
        
        ChartRefference chartrefference=new ChartRefference();
        FriendsCount=chartrefference.Returnfriends();
        OnlineCount=chartrefference.ReturnOnline();
        AdvertisementCount =chartrefference.ReturnAdvertisement();
        OtherCount=chartrefference.ReturnOther();
        PamphletCount=chartrefference.ReturnPamphlet();
        noneCount=chartrefference.Returnnone();
        
        System.out.println(FriendsCount + " result");     

        DefaultCategoryDataset Refferencedod=new DefaultCategoryDataset();
        Refferencedod.setValue(OnlineCount,"No.Of join","online");
        Refferencedod.setValue(AdvertisementCount,"No.Of join","Advertisement");
        Refferencedod.setValue(FriendsCount,"No.Of join","Friends");
        Refferencedod.setValue(PamphletCount,"No.Of join","Pamphlet");
        Refferencedod.setValue(OtherCount,"No.Of join","Other");
        Refferencedod.setValue(noneCount,"No.Of join","none");
        JFreeChart Refferencechart=ChartFactory.createBarChart("Student Record","Months","No.Of join",Refferencedod,PlotOrientation.VERTICAL,true,true,false);
     
            CategoryPlot plot=Refferencechart.getCategoryPlot();
            plot.setRangeGridlinePaint(Color.black);
            ChartPanel RefferencebarPanel=new ChartPanel(Refferencechart) ;
            RefferenceShowChart.removeAll();
            RefferenceShowChart.add(RefferencebarPanel,BorderLayout.CENTER);
            RefferenceShowChart.validate();
            

    }//GEN-LAST:event_RefferenceCharButtonActionPerformed

    private void RegistrationChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationChartButtonActionPerformed
        // TODO add your handling code here:
        
        
        

        DefaultCategoryDataset Registrationdod=new DefaultCategoryDataset();
        Registrationdod.setValue(OnlineCount,"No.Of join","online");
        Registrationdod.setValue(AdvertisementCount,"No.Of join","Advertisement");
        Registrationdod.setValue(FriendsCount,"No.Of join","Friends");
        Registrationdod.setValue(PamphletCount,"No.Of join","Pamphlet");
        Registrationdod.setValue(OtherCount,"No.Of join","Other");
        Registrationdod.setValue(noneCount,"No.Of join","none");
        JFreeChart Registrationchart=ChartFactory.createBarChart3D("Student Record","Months","No.Of join",Registrationdod,PlotOrientation.VERTICAL,true,true,false);
     
            CategoryPlot plot=Registrationchart.getCategoryPlot();
            plot.setRangeGridlinePaint(Color.black);
            ChartPanel RegistrationbarPanel=new ChartPanel(Registrationchart) ;
              RegistrationShowChart.removeAll();
             RegistrationShowChart.add(RegistrationbarPanel,BorderLayout.CENTER);
             RegistrationShowChart.validate();
          
    }//GEN-LAST:event_RegistrationChartButtonActionPerformed

    private void MonthChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthChartButtonActionPerformed
        // TODO add your handling code here:
          DefaultCategoryDataset Monthdod=new DefaultCategoryDataset();
        Monthdod.setValue(1,"No.Of join","online");
        Monthdod.setValue(2,"No.Of join","Advertisement");
        Monthdod.setValue(3,"No.Of join","Friends");
        Monthdod.setValue(4,"No.Of join","Pamphlet");
        Monthdod.setValue(5,"No.Of join","Other");
        Monthdod.setValue(6,"No.Of join","none");
        JFreeChart Monthchart=ChartFactory.createLineChart3D("Student Record","Months","No.Of join",Monthdod,PlotOrientation.VERTICAL,true,true,false);
     
            CategoryPlot plot=Monthchart.getCategoryPlot();
            plot.setRangeGridlinePaint(Color.black);
            ChartPanel MonthPanel=new ChartPanel(Monthchart) ;
            MonthShowChart.removeAll();
            MonthShowChart.add(MonthPanel,BorderLayout.CENTER);
            MonthShowChart.validate();
            MonthShowChart.setVisible(true);
    }//GEN-LAST:event_MonthChartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAnalyticalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAnalyticalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAnalyticalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAnalyticalPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminAnalyticalPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MonthChartButton;
    private com.toedter.calendar.JDateChooser MonthFromDate;
    private javax.swing.JPanel MonthShowChart;
    private com.toedter.calendar.JDateChooser MonthToDate;
    private javax.swing.JButton RefferenceCharButton;
    private com.toedter.calendar.JDateChooser RefferenceFromDate;
    private javax.swing.JPanel RefferenceShowChart;
    private com.toedter.calendar.JDateChooser RefferenceToDate;
    private javax.swing.JButton RegistrationChartButton;
    private javax.swing.JPanel RegistrationShowChart;
    private com.toedter.calendar.JDateChooser RegistratonFromDate;
    private com.toedter.calendar.JDateChooser RegistratonToDate;
    private javax.swing.JLabel ShowDate;
    private javax.swing.JLabel Showtime;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
