/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package software;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ELCOT
 */
public class Coursedetails extends javax.swing.JFrame {

    
      Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;

    
    static int price;
    static String SelectedCourse;
    
public Coursedetails() {
      con=ConnectionDb.DbConnection();
        initComponents();
        DisplayTable();
       // getColumnModel(). getColumn(). setPreferredWidth()
       Showdata.getColumnModel().getColumn(0).setWidth(400);
       Showdata.getColumnModel().getColumn(ICONIFIED).setPreferredWidth(500);
    }
   

private void DisplayTable(){
         try{
                   String sql="Select * FROM Coursedata";
                   pst =con.prepareStatement(sql);
                   rs=pst.executeQuery();
                   Showdata.setModel(DbUtils.resultSetToTableModel(rs));
                   Showdata.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                   
            
                    System.out.println("Successfully load enquirydata");
            }catch(SQLException e){
                 System.out.println("Fail to load enquirydata"+e);
             }finally{
                 try{
                    
                     pst.close();
                     System.out.println("Successfully closed database");
                 }catch(SQLException e){
                     System.out.println("Fail to lose database"+e);
                 }
             }
    }

    private void EditPrice(){
         try{
          
                   String sql="UPDATE  Coursedata SET  Price=? WHERE Course='"+SelectedCourse+"';";
                   pst =con.prepareStatement(sql);
                                                                                    //1
                   pst.setInt(1,price);    
                                                      //2                   
                   pst.executeUpdate();
                  
                   
            
                    System.out.println("Successfully update the data");
            }catch(SQLException e){
                 System.out.println("Fail update the data"+e);
             }finally{
                 try{
                    
                     pst.close();
                     System.out.println("Successfully closed database");
                 }catch(SQLException e){
                     System.out.println("Fail to lose database"+e);
                 }
             }
     }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        CourseLabel = new javax.swing.JLabel();
        CourseComboBox = new javax.swing.JComboBox<>();
        Price = new javax.swing.JTextField();
        ApplyButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Showdata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Course Details");

        RefreshButton.setBackground(new java.awt.Color(255, 255, 255));
        RefreshButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        RefreshButton.setText("Refresh");
        RefreshButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        CourseLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CourseLabel.setText("Course");

        CourseComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tally company cetification", "Tally", "Tally Prime", "Oracle", "MS Office", "C & C++ Programming", "C Programming", "C++ Programming", "HTML", "PHP Developer", "Python", "Android", "Big Data Programming", "Big Data Analytics", "Cloud Computing ", "Cyber Secure User", "Hacking Expert", "Forensic Investigator Computer Hacking", "Secure Programmer Expert - Android", "Secure Programmer Expert - PHP", "Secure Programmer Expert - Java", "Secure Programmer Expert - .NET", "Mobile Forensic Advance Security", "Security Cyber Analytics", "Network Security Administrator Expert", "Incident Handler Expert - SIHE", "Penetration Testing Expert", "Expert Security Specialist", "Certified Software Testing  ", "Expert loT Specialist (SEIS)", "Digital Marketing Expert (SDME)", "Certified DevOps Expert", "Expert Blockchain Specialist ", "DIPLOMA IN COMPUTER APPLICATION (DCA)", "HONORS DIPLOMA IN COMPUTER APPLICATION (HDCA)", "MASTER DIPLOMA IN COMPUTER APPLICATION (MDCA)", "HONORS DIPLOMA IN MULTIMEDIA PROGRAMMING (HDMP)", "MULTIMEDIA PROGRAMMING", "AUTO CADD", "SPOKEN ENGLISH", "SPOKEN ENGLISH- Level 1", "SPOKEN ENGLISH- Level 2", "SPOKEN ENGLISH- Level 3", "SPOKEN ENGLISH- Corporate Training", "DIPLOMA IN HARDWARE  NETWORK  (DHN)" }));
        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });

        Price.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        ApplyButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ApplyButton.setText("Apply");
        ApplyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });

        Showdata.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Showdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Showdata);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(155, 155, 155)
                        .addComponent(RefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(CourseLabel)
                                .addGap(70, 70, 70)
                                .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(ApplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jScrollPane3)))
                        .addGap(102, 102, 102))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RefreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseLabel)
                    .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApplyButton))
                .addGap(144, 144, 144))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        // TODO add your handling code here:
        price=Integer.valueOf( Price.getText());
        SelectedCourse=CourseComboBox.getSelectedItem().toString();
        
        
        EditPrice();
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
          DisplayTable();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminOptionForm adminoptionform=new AdminOptionForm();
        adminoptionform.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coursedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coursedetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JComboBox<String> CourseComboBox;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JTextField Price;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTable Showdata;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
