//package
package software;

//imports
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class EnquiryForm extends javax.swing.JFrame {
    
    //created objects  
    static String Firstname;
    static String Lastname;
    static String Fathername;
    static String Mothername;
    static String Instrutename;
    static String Studentnumber;
    static String Contactnumber;
    static String Addharnumber;
    static String Mailid;
    static String Course;
    static String address;
    static String Religion;
    static String Year=null;
    static String AcademyBackground;
    static String Gender;
    static String Institute=null;
    static String Dob;
    static String PG;
    static String Group;
    static String StudentWa;
    static String ParentsWa;
    static String dateTime;
    static long administrationnumber;
    static String aboutMyfs;
    static String Referncename=null;
    
    //for date
    SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss");
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    
    //sqlite database connection   
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    //main class
    public EnquiryForm() {
        
        //database connection
        con=ConnectionDb.DbConnection();
        
        //declare jcomponets
        initComponents();
        
        //calling class
        Administrationnumber();
        ShowAdminstration.setText(String.valueOf(administrationnumber));
        
        //Declare jcompponet to be visible false
        referenceName.setVisible(false);
        ReferenceName.setVisible(false);
        con=ConnectionDb.DbConnection();
        CourseComboBox.setSelectedItem(null);
        AcademyBackgroundComboBox.setSelectedItem(null);
        InstituteLabel.setVisible(false);
        InstruteName.setVisible(false);
        yearLabel.setVisible(false);
        YearComboBox.setVisible(false);
        acaLabel.setVisible(false);
        AcademyBackgroundComboBox.setVisible(false);
        groupLabel.setVisible(false);
        GetGroup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ShowAdminstration = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MaleRadioButton = new javax.swing.JRadioButton();
        FemaleRadioButton = new javax.swing.JRadioButton();
        FatherName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        SchoolRadioButton = new javax.swing.JRadioButton();
        CollegeRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        OtherGenderRadioButton = new javax.swing.JRadioButton();
        EmployeeRadioButton = new javax.swing.JRadioButton();
        UnEmployeeRadioButton = new javax.swing.JRadioButton();
        OtherEducationRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        InstruteName = new javax.swing.JTextField();
        InstituteLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        YearComboBox = new javax.swing.JComboBox<>();
        acaLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        GetGroup = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        GetReligion = new javax.swing.JTextField();
        AcademyBackgroundComboBox = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        MotherName = new javax.swing.JTextField();
        DOB = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        CourseComboBox = new javax.swing.JComboBox<>();
        gffbfg = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        StudentNumber = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        MailId = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        PGName = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JTextField();
        ParentwaCheckBox = new javax.swing.JCheckBox();
        StudentwaCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        AdvertisementRadioButton = new javax.swing.JRadioButton();
        OnlineRadioButton = new javax.swing.JRadioButton();
        FriendsRadioButton = new javax.swing.JRadioButton();
        PamphletRadioButton = new javax.swing.JRadioButton();
        referenceName = new javax.swing.JLabel();
        ReferenceName = new javax.swing.JTextField();
        OtherEduRadioButton = new javax.swing.JRadioButton();
        NoneRadioButton = new javax.swing.JRadioButton();
        ClearButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Enquiry Form");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Administration Number");

        ShowAdminstration.setEditable(false);
        ShowAdminstration.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(ShowAdminstration, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ShowAdminstration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("First Name");

        FirstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Father Name");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Gender");

        MaleRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        MaleRadioButton.setText("Male");
        MaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRadioButtonActionPerformed(evt);
            }
        });

        FemaleRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FemaleRadioButton.setText("Female");
        FemaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleRadioButtonActionPerformed(evt);
            }
        });

        FatherName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Education");

        SchoolRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SchoolRadioButton.setText("School");
        SchoolRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolRadioButtonActionPerformed(evt);
            }
        });

        CollegeRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CollegeRadioButton.setText("College");
        CollegeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollegeRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Last Name");

        LastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        OtherGenderRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OtherGenderRadioButton.setText("Other");
        OtherGenderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherGenderRadioButtonActionPerformed(evt);
            }
        });

        EmployeeRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EmployeeRadioButton.setText("Employee");
        EmployeeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeRadioButtonActionPerformed(evt);
            }
        });

        UnEmployeeRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UnEmployeeRadioButton.setText("UnEmployee");
        UnEmployeeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnEmployeeRadioButtonActionPerformed(evt);
            }
        });

        OtherEducationRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OtherEducationRadioButton.setText("Other");
        OtherEducationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherEducationRadioButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Date Of Birth");

        InstruteName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        InstruteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstruteNameActionPerformed(evt);
            }
        });

        InstituteLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        InstituteLabel.setText("Institute Name");

        yearLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearLabel.setText("Year");

        YearComboBox.setEditable(true);
        YearComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        YearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Std", "2 Std", "3 Std", "4 Std", "5 Std", "6 St", "7 Std", "8 Std", "9 Std", "10 Std", "11 Std", "12 Std", "1st year", "2nd year", "3rd year", "4th year" }));
        YearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearComboBoxActionPerformed(evt);
            }
        });

        acaLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        acaLabel.setText("Academy background");

        groupLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        groupLabel.setText("Group");

        GetGroup.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("Religion");

        GetReligion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GetReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetReligionActionPerformed(evt);
            }
        });

        AcademyBackgroundComboBox.setEditable(true);
        AcademyBackgroundComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AcademyBackgroundComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "State board", "CBSE", "ICSE", "Anna university", "Madras university ", "Other   " }));
        AcademyBackgroundComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcademyBackgroundComboBoxActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel34.setText("Mother Name");

        MotherName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        DOB.setDateFormatString("dd-MMM-yyyy");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19)
                    .addComponent(InstituteLabel)
                    .addComponent(acaLabel)
                    .addComponent(jLabel23)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(OtherGenderRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FemaleRadioButton)
                                .addComponent(MaleRadioButton)
                                .addComponent(FirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(FatherName)
                                .addComponent(GetReligion))
                            .addComponent(AcademyBackgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InstruteName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(yearLabel)
                            .addComponent(groupLabel)
                            .addComponent(jLabel8)
                            .addComponent(jLabel34)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(EmployeeRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(UnEmployeeRadioButton))
                    .addComponent(OtherEducationRadioButton)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(CollegeRadioButton)
                            .addGap(38, 38, 38)
                            .addComponent(SchoolRadioButton))
                        .addComponent(MotherName, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(YearComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 219, Short.MAX_VALUE)
                        .addComponent(GetGroup, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(MaleRadioButton)
                    .addComponent(jLabel8)
                    .addComponent(CollegeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SchoolRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FemaleRadioButton)
                    .addComponent(EmployeeRadioButton)
                    .addComponent(UnEmployeeRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtherGenderRadioButton)
                    .addComponent(OtherEducationRadioButton))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(GetReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GetGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupLabel)
                            .addComponent(acaLabel))
                        .addGap(77, 77, 77))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearLabel)
                            .addComponent(InstituteLabel)
                            .addComponent(InstruteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AcademyBackgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel32.setText("Course");

        CourseComboBox.setEditable(true);
        CourseComboBox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Company Introduction", "Star C Programming", "Star C++ Programming", "Star HTML", "Star PHP Developer", "Star Python", "Star Android", "Star Big Data Programming", "Star Big Data Analytics", "Star Cloud Computing", "Star Cyber Secure User", "Ethical Hacking Expert", "Star Forensic Investigator Computer Hacking - 007", "Star Secure Programmer Expert - Android", "Star Secure Programmer Expert - Java", "Star Secure Programmer Expert - PHP", "Star Secure Programmer Expert - NET", "Star Mobile Forensic Advance Security", "Star Security Cyber Analytics", "Star Network Security Administrator Expert", "Star Incident Handler Expert - SIHE", "Star Penetration Testing Expert", "Star Expert Security Specialist", "Star Certified Software Testing", "Star Expert loT Specialist (SEIS)", "Star Digital Marketing Expert (SDME)", "Star Certified DevOps Expert", "Star Expert Blockchain Specialist" }));
        CourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(136, 136, 136)
                .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        gffbfg.setBackground(new java.awt.Color(51, 153, 255));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel33.setText("Address");

        Address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel35.setText("Student Number");

        StudentNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        StudentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentNumberActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel37.setText("Mail Id");

        MailId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        MailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailIdActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel38.setText("Parent/Guardian Name");

        PGName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel39.setText("Contact Number");

        ContactNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });

        ParentwaCheckBox.setText("Whatsapp Number");

        StudentwaCheckBox.setText("Whatsapp Number");

        javax.swing.GroupLayout gffbfgLayout = new javax.swing.GroupLayout(gffbfg);
        gffbfg.setLayout(gffbfgLayout);
        gffbfgLayout.setHorizontalGroup(
            gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gffbfgLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(StudentNumber)
                        .addComponent(PGName))
                    .addComponent(ParentwaCheckBox))
                .addGap(45, 45, 45)
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37))
                .addGap(42, 42, 42)
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentwaCheckBox)
                    .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MailId, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(ContactNumber)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gffbfgLayout.setVerticalGroup(
            gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gffbfgLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(PGName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gffbfgLayout.createSequentialGroup()
                        .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gffbfgLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(StudentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gffbfgLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ParentwaCheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gffbfgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StudentwaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(34, 34, 34)))
                .addGroup(gffbfgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gffbfgLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel33)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gffbfgLayout.createSequentialGroup()
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel36.setText("How do You Come to Know about FirstStep Institute?");

        AdvertisementRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AdvertisementRadioButton.setText("Advertisement");
        AdvertisementRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvertisementRadioButtonActionPerformed(evt);
            }
        });

        OnlineRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OnlineRadioButton.setText("Online");
        OnlineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineRadioButtonActionPerformed(evt);
            }
        });

        FriendsRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        FriendsRadioButton.setText("Friends");
        FriendsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsRadioButtonActionPerformed(evt);
            }
        });

        PamphletRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PamphletRadioButton.setText("Pamphlet");
        PamphletRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PamphletRadioButtonActionPerformed(evt);
            }
        });

        referenceName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        referenceName.setText("Reference Name");

        ReferenceName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        OtherEduRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OtherEduRadioButton.setText("Other");
        OtherEduRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherEduRadioButtonActionPerformed(evt);
            }
        });

        NoneRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NoneRadioButton.setText("None ");
        NoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(referenceName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(OtherEduRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addGap(62, 62, 62))
                            .addComponent(AdvertisementRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OnlineRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(FriendsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(PamphletRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addComponent(NoneRadioButton))
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AdvertisementRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OnlineRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FriendsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PamphletRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtherEduRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NoneRadioButton))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceName)
                    .addComponent(ReferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        ClearButton.setBackground(new java.awt.Color(255, 255, 255));
        ClearButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(255, 255, 255));
        SaveButton.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gffbfg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(gffbfg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:

        Firstname=FirstName.getText();
        Lastname=LastName.getText();
        Fathername=FatherName.getText();
        Mothername=MotherName.getText();
        Instrutename=InstruteName.getText();
        Studentnumber=StudentNumber.getText();
        Contactnumber=ContactNumber.getText();

        Mailid=MailId.getText().toLowerCase();
        Course=CourseComboBox.getSelectedItem().toString();

        AcademyBackground=AcademyBackgroundComboBox.getSelectedItem().toString();
        Religion=GetReligion.getText();

        PG=PGName.getText();
        Group=GetGroup.getText();
        dateTime=formatter.format(date);
        address=Address.getText();

        Referncename=ReferenceName.getText();
        if(OnlineRadioButton.isSelected()){
            Referncename=null;
        }
        if(AdvertisementRadioButton.isSelected()){
            Referncename=null;
        }
        if(PamphletRadioButton.isSelected()){
            Referncename=null;
        }
        if(OtherEduRadioButton.isSelected()){
            Referncename=null;
        }
        if(NoneRadioButton.isSelected()){
            Referncename=null;
        }

        aboutMyfs=null;
        if(OnlineRadioButton.isSelected()){
            aboutMyfs="Online";
        }
        if(AdvertisementRadioButton.isSelected()){
            aboutMyfs="Advertisement";
        }
        if(FriendsRadioButton.isSelected()){
            aboutMyfs="Friends";
        }
        if(PamphletRadioButton.isSelected()){
            aboutMyfs="Pamphlet";
        }
        if(OtherEduRadioButton.isSelected()){
            aboutMyfs="Other";
        }
        if(NoneRadioButton.isSelected()){
            aboutMyfs="none";
        }

        StudentWa=null;
        if(StudentwaCheckBox.isSelected()){
            StudentWa="yes";
        }else{
            StudentWa="no";
        }

        ParentsWa=null;
        if(ParentwaCheckBox.isSelected()){
            ParentsWa="yes";
        }else{
            ParentsWa="no";
        }
        Gender=null;
        if(MaleRadioButton.isSelected()){
            Gender="Male";
        }if(FemaleRadioButton.isSelected()){
            Gender="Female";
        } if(OtherGenderRadioButton.isSelected()){
            Gender="Other";
        }

        Institute =null;
        if(SchoolRadioButton.isSelected()){
            Institute ="School";
        }if(CollegeRadioButton.isSelected()){
            Institute ="College";
        }if(OtherEducationRadioButton.isSelected()){
            Institute ="Other";
        }if(EmployeeRadioButton.isSelected()){
            Institute ="Employee";
        }if(UnEmployeeRadioButton.isSelected()){
            Institute="UnEmployee";
        }

        try{
            String sql="INSERT INTO Enquriytable VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst =con.prepareStatement(sql);

            pst.setLong(1,  administrationnumber);    //1
            pst.setString(2, Firstname);    //2
            pst.setString(3, Lastname);  //3
            pst.setString(4, Fathername);  //4
            pst.setString(5, Mothername);  //5
            pst.setString(6,  Religion);  //6
            pst.setString(7, ((JTextField)DOB.getDateEditor().getUiComponent()).getText());   //7
            pst.setString(8,  Gender);  //8
            pst.setString(9, Institute);    //9
            pst.setString(10,  Instrutename);    //10
            pst.setString(11,  AcademyBackground);    //11
            pst.setString(12, Group);   //12
            pst.setString(13, Year);   //13
            pst.setString(14,  Course);   //14
            pst.setString(15, Studentnumber);    //15
            pst.setString(16, Contactnumber);    //16
            pst.setString(17, Mailid);    //17
            pst.setString(18, address);   //18
            pst.setString(19,formatter.format(date));  //19
            pst.setString(20,aboutMyfs);   //20
            pst.setString(21, Referncename);   //21

            JOptionPane.showMessageDialog(this,"Saved,");
            pst.execute();

            System.out.println("Saved student data Successfully");

        }catch(HeadlessException | SQLException e){
            System.out.println("Fail to save Student data"+e);
        }finally{
            try{

                pst.close();
                System.out.println("Successfully closed the data base");
            }catch(SQLException e){
                System.out.println("Fail toclose the data base "+e);
            }
        }
        // TODO add your handling code here:
        OptionForm optionform =new OptionForm();
        optionform.setVisible(true);
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        FirstName.setText(null);
        LastName.setText(null);
        FatherName.setText(null);
        MotherName.setText(null);
        InstruteName.setText(null);
        MailId.setText(null);

        GetReligion.setText(null);
        PGName.setText(null);
        GetGroup.setText(null);

        Address.setText(null);

        OnlineRadioButton.setSelected(false);
        AdvertisementRadioButton.setSelected(false);
        PamphletRadioButton.setSelected(false);
        OtherEduRadioButton.setSelected(false);
        NoneRadioButton.setSelected(false);
        FriendsRadioButton.setSelected(false);

        StudentwaCheckBox.setSelected(false);
        ParentwaCheckBox.setSelected(false);
        MaleRadioButton.setSelected(false);
        OtherGenderRadioButton.setSelected(false);
        FemaleRadioButton.setSelected(false);
        StudentNumber.setText(null);
        ContactNumber.setText(null);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void NoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneRadioButtonActionPerformed
        // TODO add your handling code here:
        if(NoneRadioButton.isSelected()){

            AdvertisementRadioButton.setSelected(false);
            FriendsRadioButton.setSelected(false);
            OnlineRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            referenceName.setVisible(false);
            ReferenceName.setVisible(false);
        }
    }//GEN-LAST:event_NoneRadioButtonActionPerformed

    private void OtherEduRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherEduRadioButtonActionPerformed
        // TODO add your handling code here:
        if(OtherEduRadioButton.isSelected()){

            AdvertisementRadioButton.setSelected(false);
            FriendsRadioButton.setSelected(false);
            OnlineRadioButton.setSelected(false);
            PamphletRadioButton.setSelected(false);
            NoneRadioButton.setSelected(false);
            referenceName.setVisible(false);
            ReferenceName.setVisible(false);
        }
    }//GEN-LAST:event_OtherEduRadioButtonActionPerformed

    private void PamphletRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PamphletRadioButtonActionPerformed
        // TODO add your handling code here:
        if(PamphletRadioButton.isSelected()){

            AdvertisementRadioButton.setSelected(false);
            FriendsRadioButton.setSelected(false);
            OnlineRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            NoneRadioButton.setSelected(false);
            referenceName.setVisible(false);
            ReferenceName.setVisible(false);
        }
    }//GEN-LAST:event_PamphletRadioButtonActionPerformed

    private void FriendsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsRadioButtonActionPerformed
        // TODO add your handling code here:
        if(FriendsRadioButton.isSelected()){

            AdvertisementRadioButton.setSelected(false);
            OnlineRadioButton.setSelected(false);
            PamphletRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            NoneRadioButton.setSelected(false);
            referenceName.setVisible(true);
            ReferenceName.setVisible(true);
        }
    }//GEN-LAST:event_FriendsRadioButtonActionPerformed

    private void OnlineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineRadioButtonActionPerformed
        // TODO add your handling code here:
        if(OnlineRadioButton.isSelected()){

            AdvertisementRadioButton.setSelected(false);
            FriendsRadioButton.setSelected(false);
            PamphletRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            NoneRadioButton.setSelected(false);
            referenceName.setVisible(false);
            ReferenceName.setVisible(false);
        }
    }//GEN-LAST:event_OnlineRadioButtonActionPerformed

    private void AdvertisementRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvertisementRadioButtonActionPerformed
        // TODO add your handling code here:
        if(AdvertisementRadioButton.isSelected()){
            OnlineRadioButton.setSelected(false);
            FriendsRadioButton.setSelected(false);
            PamphletRadioButton.setSelected(false);
            OtherEduRadioButton.setSelected(false);
            NoneRadioButton.setSelected(false);
            referenceName.setVisible(false);
            ReferenceName.setVisible(false);
        }
    }//GEN-LAST:event_AdvertisementRadioButtonActionPerformed

    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void MailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailIdActionPerformed

    private void StudentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentNumberActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void CourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboBoxActionPerformed
        // TODO add your handling code here:
        CourseComboBox.addItem("Company Introduction");
        CourseComboBox.addItem("Star C Programming");
        CourseComboBox.addItem("Star C++ Programming");
        CourseComboBox.addItem("Star HTML");
        CourseComboBox.addItem("Star PHP Developer");
        CourseComboBox.addItem(";Star Python");
        CourseComboBox.addItem("Star Android");
        CourseComboBox.addItem("Star Big Data Programming");
        CourseComboBox.addItem("Star Big Data Analytics");
        CourseComboBox.addItem("Star Cloud Computing");
        CourseComboBox.addItem("Star Cyber Secure User");
        CourseComboBox.addItem("Ethical Hacking Expert");
        CourseComboBox.addItem("star Forensic Investigator Computer Hacking - 007");
        CourseComboBox.addItem("Star Secure Programmer Expert - Android");
        CourseComboBox.addItem("Star Secure Programmer Expert - PHP");
        CourseComboBox.addItem("Star Secure Programmer Expert - Java");
        CourseComboBox.addItem(" Star Secure Programmer Expert - NET");
        CourseComboBox.addItem("Star Mobile Forensic Advance Security");
        CourseComboBox.addItem("Star Security Cyber Analytics");
        CourseComboBox.addItem("Star Network Security Administrator Expert");
        CourseComboBox.addItem("Star Incident Handler Expert - SIHE");
        CourseComboBox.addItem("Star Penetration Testing Expert");
        CourseComboBox.addItem("Star Expert Security Specialist");
        CourseComboBox.addItem("Star Certified Software Testing");
        CourseComboBox.addItem("Star Expert loT Specialist (SEIS)");
        CourseComboBox.addItem("Star Digital Marketing Expert (SDME)");
        CourseComboBox.addItem("Star Certified DevOps Expert");
        CourseComboBox.addItem("Star Expert Blockchain Specialist");
        CourseComboBox.setVisible(true);
        CourseComboBox.setEditable(true);
    }//GEN-LAST:event_CourseComboBoxActionPerformed

    private void AcademyBackgroundComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcademyBackgroundComboBoxActionPerformed
        // TODO add your handling code here:
        AcademyBackgroundComboBox.addItem("State board");
        AcademyBackgroundComboBox.addItem("CBSE");
        AcademyBackgroundComboBox.addItem("ICSE");
        AcademyBackgroundComboBox.addItem("Anna university");
        AcademyBackgroundComboBox.addItem("Madras university");
        AcademyBackgroundComboBox.addItem("Other");
        AcademyBackgroundComboBox.setEditable(true);
        AcademyBackgroundComboBox.setVisible(true);
    }//GEN-LAST:event_AcademyBackgroundComboBoxActionPerformed

    private void GetReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetReligionActionPerformed

    private void YearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearComboBoxActionPerformed
        // TODO add your handling code here:

        YearComboBox.addItem("1 Std");
        YearComboBox.addItem("2 Std");
        YearComboBox.addItem("3 Std");
        YearComboBox.addItem("4 Std");
        YearComboBox.addItem("5 Std");
        YearComboBox.addItem("6 Std");
        YearComboBox.addItem("7 Std");
        YearComboBox.addItem("8 Std");
        YearComboBox.addItem("9 Std");
        YearComboBox.addItem("10 Std");
        YearComboBox.addItem("11 Std");
        YearComboBox.addItem("12 Std");
        YearComboBox.addItem("1st year");
        YearComboBox.addItem("2nd year");
        YearComboBox.addItem("3rd year");
        YearComboBox.addItem("4th year");
        YearComboBox.setVisible(true);
    }//GEN-LAST:event_YearComboBoxActionPerformed

    private void InstruteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstruteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstruteNameActionPerformed

    private void OtherEducationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherEducationRadioButtonActionPerformed
        // TODO add your handling code here:
        if(OtherEducationRadioButton.isSelected()){
            CollegeRadioButton.setSelected(false);
            SchoolRadioButton.setSelected(false);

            EmployeeRadioButton.setSelected(false);
            UnEmployeeRadioButton.setSelected(false);
            InstituteLabel.setVisible(false);
            InstruteName.setVisible(false);
            yearLabel.setVisible(false);
            YearComboBox.setVisible(false);
            acaLabel.setVisible(false);
            AcademyBackgroundComboBox.setVisible(false);
            groupLabel.setVisible(false);
            GetGroup.setVisible(false);
        }
    }//GEN-LAST:event_OtherEducationRadioButtonActionPerformed

    private void UnEmployeeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnEmployeeRadioButtonActionPerformed
        // TODO add your handling code here:
        if( UnEmployeeRadioButton.isSelected()){
            CollegeRadioButton.setSelected(false);
            SchoolRadioButton.setSelected(false);
            EmployeeRadioButton.setSelected(false);
            OtherEducationRadioButton.setSelected(false);
            InstituteLabel.setVisible(false);
            InstruteName.setVisible(false);
            yearLabel.setVisible(false);
            YearComboBox.setVisible(false);
            acaLabel.setVisible(false);
            AcademyBackgroundComboBox.setVisible(false);
            groupLabel.setVisible(false);
            GetGroup.setVisible(false);
        }
    }//GEN-LAST:event_UnEmployeeRadioButtonActionPerformed

    private void EmployeeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeRadioButtonActionPerformed
        // TODO add your handling code here:
        if(EmployeeRadioButton.isSelected()){
            CollegeRadioButton.setSelected(false);
            SchoolRadioButton.setSelected(false);
            OtherEducationRadioButton.setSelected(false);
            UnEmployeeRadioButton.setSelected(false);
            InstituteLabel.setVisible(false);
            InstruteName.setVisible(false);
            yearLabel.setVisible(false);
            YearComboBox.setVisible(false);
            acaLabel.setVisible(false);
            AcademyBackgroundComboBox.setVisible(false);
            groupLabel.setVisible(false);
            GetGroup.setVisible(false);
        }
    }//GEN-LAST:event_EmployeeRadioButtonActionPerformed

    private void OtherGenderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherGenderRadioButtonActionPerformed
        // TODO add your handling code here:
        if(OtherGenderRadioButton.isSelected()){
            FemaleRadioButton.setSelected(false);
            MaleRadioButton.setSelected(false);

        }
    }//GEN-LAST:event_OtherGenderRadioButtonActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void CollegeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollegeRadioButtonActionPerformed
        // TODO add your handling code here:
        if(CollegeRadioButton.isSelected()){
            SchoolRadioButton.setSelected(false);
            EmployeeRadioButton.setSelected(false);
            OtherEducationRadioButton.setSelected(false);

            UnEmployeeRadioButton.setSelected(false);
            InstituteLabel.setVisible(true);
            InstruteName.setVisible(true);
            yearLabel.setVisible(true);
            YearComboBox.setVisible(true);
            acaLabel.setVisible(true);
            AcademyBackgroundComboBox.setVisible(true);
            groupLabel.setVisible(true);
            GetGroup.setVisible(true);
        }
    }//GEN-LAST:event_CollegeRadioButtonActionPerformed

    private void SchoolRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolRadioButtonActionPerformed
        // TODO add your handling code here:
        if(SchoolRadioButton.isSelected()){
            CollegeRadioButton.setSelected(false);
            EmployeeRadioButton.setSelected(false);
            OtherEducationRadioButton.setSelected(false);
            EmployeeRadioButton.setSelected(false);
            InstituteLabel.setVisible(true);
            InstruteName.setVisible(true);
            yearLabel.setVisible(true);
            YearComboBox.setVisible(true);
            acaLabel.setVisible(true);
            AcademyBackgroundComboBox.setVisible(true);
            groupLabel.setVisible(true);
            GetGroup.setVisible(true);

        }
    }//GEN-LAST:event_SchoolRadioButtonActionPerformed

    private void FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameActionPerformed

    private void FemaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleRadioButtonActionPerformed
        // TODO add your handling code here:
        if(FemaleRadioButton.isSelected()){
            MaleRadioButton.setSelected(false);
            OtherGenderRadioButton.setSelected(false);
            EmployeeRadioButton.setSelected(false);
            UnEmployeeRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_FemaleRadioButtonActionPerformed

    private void MaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRadioButtonActionPerformed
        // TODO add your handling code here:
        if(MaleRadioButton.isSelected()){
            FemaleRadioButton.setSelected(false);
            OtherGenderRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_MaleRadioButtonActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OptionForm optionform =new OptionForm();
        optionform.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
  /*  private void Administrationnumber(){
        int Administrationnumber ;
         try{
                   String sql= "SELECT MAX() FROM Registrationtable";
                   pst =con.prepareStatement(sql);
                   rs= pst.executeQuery();
                   
                  
                     
                   if(rs.next()){
                     Administrationnumber =rs.getInt("COUNT");
                       administrationnumber=10000+Administrationnumber;
                   }
                         
                        System.out.println("Successfully count the administration number");
          
                 
            
             }catch(SQLException e){
                 System.out.println("Fail to count the  administration number"+e);
             }finally{
                 try{
                    
                     pst.close();
                     System.out.println("Successfully close the data base");
                 }catch(SQLException e){
                     System.out.println("Fail to  cllose the data base"+e);
                 }
             }
        
    }
    
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnquiryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnquiryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnquiryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnquiryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EnquiryForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AcademyBackgroundComboBox;
    private javax.swing.JTextField Address;
    private javax.swing.JRadioButton AdvertisementRadioButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JRadioButton CollegeRadioButton;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JComboBox<String> CourseComboBox;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JRadioButton EmployeeRadioButton;
    public static javax.swing.JTextField FatherName;
    private javax.swing.JRadioButton FemaleRadioButton;
    private javax.swing.JTextField FirstName;
    private javax.swing.JRadioButton FriendsRadioButton;
    private javax.swing.JTextField GetGroup;
    private javax.swing.JTextField GetReligion;
    private javax.swing.JLabel InstituteLabel;
    private javax.swing.JTextField InstruteName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MailId;
    private javax.swing.JRadioButton MaleRadioButton;
    private javax.swing.JTextField MotherName;
    private javax.swing.JRadioButton NoneRadioButton;
    private javax.swing.JRadioButton OnlineRadioButton;
    private javax.swing.JRadioButton OtherEduRadioButton;
    private javax.swing.JRadioButton OtherEducationRadioButton;
    private javax.swing.JRadioButton OtherGenderRadioButton;
    private javax.swing.JTextField PGName;
    private javax.swing.JRadioButton PamphletRadioButton;
    private javax.swing.JCheckBox ParentwaCheckBox;
    private javax.swing.JTextField ReferenceName;
    private javax.swing.JButton SaveButton;
    private javax.swing.JRadioButton SchoolRadioButton;
    private javax.swing.JTextField ShowAdminstration;
    private javax.swing.JTextField StudentNumber;
    private javax.swing.JCheckBox StudentwaCheckBox;
    private javax.swing.JRadioButton UnEmployeeRadioButton;
    private javax.swing.JComboBox<String> YearComboBox;
    private javax.swing.JLabel acaLabel;
    private javax.swing.JPanel gffbfg;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel referenceName;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
